language: ruby
cache: bundler
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - gem cleanup bundler
script: "bundle exec rspec"
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
jobs:
  exclude:
  - rvm: 2.2
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.3
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails_6.0.gemfile
